services:
  - type: web
    name: cafe-app-frontend
    env: docker
    plan: free
    dockerfilePath: ./frontend.dockerfile
    dockerContext: .
    healthCheckPath: /
    envVars:
      - key: VITE_API_BASE_URL
        value: https://cafe-app-backend-guv2.onrender.com